name: drivesync
description: Intelligent Drive Monitoring & Safety System

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core functionality
  shared_preferences: ^2.2.2
  
  # State management - MVVM
  provider: ^6.1.1
  flutter_bloc: ^8.1.3
  
  # Maps and location
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  geolocator: ^10.1.0
  location: ^5.0.3
  geocoding: ^3.0.0
  
  # HTTP and API calls
  dio: ^5.3.2
  http: ^1.1.0
  
  # Sensors
  sensors_plus: ^4.0.2
  
  # Image and camera functionality
  image_picker: ^1.0.4
  
  # Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Notifications
  flutter_local_notifications: ^19.0.0
  
  # UI Components
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  
  # Utilities
  uuid: ^4.0.0
  
  # Animations
  lottie: ^2.7.0
  
  # Permissions
  permission_handler: ^11.1.0
  
  # Device info
  device_info_plus: ^9.1.0
  
  # URL launcher for external links
  url_launcher: ^6.2.1
  
  # Date formatting
  intl: ^0.19.0
  
  # Math operations for AI calculations
  collection: ^1.17.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/fonts/

  # Fonts
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700